language: node_js
node_js: "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  - 'npm run vscode:prepublish'
  - 'npm install -g vsce'
  - 'vsce package'
deploy:
  provider: releases
  api_key:  ${DEPLOY_TOKEN}
  file:
    - "vscode-apache-camel-0.0.1.vsix"
  skip_cleanup: true
  overwrite: true
  on:
    branch:  master
  branches:
    only:
      - master
cache:
  directories:
    - "node_modules"  
env: DISPLAY=:99
